# more info: https://dart.dev/guides/language/analysis-options
# all rules: https://dart.dev/tools/linter-rules

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false
    # directives_ordering: true

    annotate_redeclares: true
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    cast_nullable_to_non_nullable: true
    join_return_with_assignment: true
    noop_primitive_operations: true
    only_throw_errors: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_single_quotes: true
    sized_box_shrink_expand: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
