name: thc
description: "Guided meditation, streamed live to people in prison."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  agora_uikit: ^1.3.8
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  meta: ^1.11.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  cloud_firestore: ^4.16.0
  svg_path_parser: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter:
  uses-material-design: true
  assets:
    - assets/
