name: thc
description: "Guided meditation, streamed live to people in prison."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  meta: ^1.11.0
  provider: ^6.1.2
  agora_rtc_engine: ^6.3.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/
