name: thc
description: "Guided meditation, streamed live to people in prison."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  meta: ^1.12.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  http: ^1.2.1

  appinio_video_player: ^1.3.0
  cupertino_icons: ^1.0.8

  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  email_validator: ^2.1.17

  dio: ^5.4.0
  universal_html: ^2.2.4
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg_files/
  fonts:
    - family: roboto mono
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
        - asset: assets/fonts/roboto_mono_italic.ttf
          style: italic
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard.ttf
