name: thc
description: "Guided meditation, streamed live to people in prison."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.1.2
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  meta: ^1.15.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  http: ^1.2.2

  appinio_video_player: ^1.3.0
  cupertino_icons: ^1.0.8

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  email_validator: ^2.1.17

  dio: ^5.6.0
  universal_html: ^2.2.4
  firebase_messaging: ^14.9.4
  file_picker: ^8.0.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg_files/
  fonts:
    - family: roboto mono
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
        - asset: assets/fonts/roboto_mono_italic.ttf
          style: italic
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard.ttf
